### ISSUE TITLE
[MILESTONE CHECKLIST] Elife Innovation Sprint

### ISSUE THREAD

**Issue by NatalieThurlby** [very-good-science/our-handbook#26]
During the eLife Innovation Sprint, we decided on four goals:
- [ ] __1__ Complete at least two more sections of the template handbook. Currently only the [welcome page](https://very-good-science.github.io/our-handbook/template/welcome.html) template is filled in, but we’d like to have content for at least two more sections. These might be sections that we already have placeholder pages for like “our team” (#18), or they might be new ideas that the participants come up with e.g. “working on side projects”, “getting the most out of one-to-ones”, or “writing preregistration”. These might also look like resources! If we get more done, that's even better!
    - [ ] First section
    - [ ] Second section
- [ ] __2__ Create an example handbook using the template repository. This will help us to show potential users what the end goal is of the handbook, e.g. “The Jean Golding Institute’s Data Scientist’s handbook”. It will also help us to do our next aim…
- [ ] __3__ Improve instructions for using the template repository. We have some instructions, but they are missing some information and need testing to ensure they are easy to use.
- [ ] __4__ Improve contribution guidelines for future contributors. For example, we would like to be able to collect good ideas for resources for the handbook from people who’ve never used GitHub before, but that have a great resource that they use with their group.

**Comment by NatalieThurlby** [comment]
I'll link more issues here as we decide on them :)

**Comment by NatalieThurlby** [comment]
The sprint's now over. We did a good job with our aims. Only testing out the handbook ourselves left to go!
